---
title: "Tidyr"
author: "Jeremy Notch"
date: "December 1, 2017"
output: html_document
---

```{r}
library(tidyverse)
```

# example datasets
```{r}
AirPassengers
mpg
```
```{r}
## wide format
gap_wide <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder_wide.csv')


## yesterdays data format
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

head(gap_wide)

##"gather()" use gather to turn gap_wide into a long format dataset

gap_long <- gap_wide %>% 
  gather(key=obstype_year, 
         value = obs_values)

gap_long <- gap_wide %>% 
  gather(key = obstype_year, 
         value = obs_values, 
         dplyr:: starts_with("pop"),
         dplyr:: starts_with("lifeExp"),
         dplyr:: starts_with("gdpPercap"))

head(gap_long)
tail(gap_long)

## the :: indicates starts_with comes from the dplyr package
```

```{r}
gap_long<- gap_wide %>% 
  gather(key = obstype_year,
         value = obs_values, 
        - continent, -country)

head(gap_long)
```
## separate out the year
```{r}
gap_long<- gap_wide %>% 
  gather(key = obstype_year,
         value = obs_values, 
        - continent, -country) %>% 
  separate(obstype_year, 
           into = c ("obs_type", "year"),
           sep = "_",
           convert = T)

head(gap_long)
```
## plot long format data

```{r}
life_df <-  gap_long %>% 
  filter(obs_type == "lifeExp",
         continent == "Americas")

head(life_df)

ggplot(data= life_df, aes(x=year, y=obs_values, color = country))+
  geom_line()

```
```{r}
#Using gap_long, calculate and plot the the mean life expectancy for each continent over time from 1982 to 2007. Give your plot a title and assign x and y labels. Hint: use the dplyr::group_by() and dplyr::summarize() functions.

mean_life.df <- gap_long %>% 
  filter(obs_type == "lifeExp",
         year >= 1982,
         year<=2007) %>% 
  group_by(continent, year) %>% 
  summarize(obs_values = mean(obs_values))
  
head(mean_life.df)

ggplot(data= mean_life.df, aes(x=year, y=obs_values, color = continent))+
  geom_line()+
  labs(title = "life expectancy",
       x = "year",
       y = "Age (years)",
       color = "Continent")+
  theme_bw()

```
## spread
```{r}
head(gap_long)

gap_normal <- gap_long %>% 
  spread(key = obs_type,
         value = obs_values)

head(gap_normal)
```
### exercise
```{r}
head(gap_long)
head(gap_wide)
head(new.gap.wide)

gap_wide_new <- gap_long %>% 
  # first unite obs_type and year into a new column called var_names. Separate by _
  unite(col = var_names, obs_type, year, sep = "_") %>% 
  # then spread var_names out by key-value pair.
  spread(key = var_names, value = obs_values)

str(gap_wide_new)

```



